### ISSUE TITLE
Find a way to approve new models

### ISSUE THREAD

**Issue by victorlap** [victorlap/laravel-approvable#2]
Currently it is not supported to approve new models, I think it is within the scope of this package to do that.

**Comment by asivaneswaran** [comment]
Hey, so I am looking to implement your package and I was wondering, can't you just create a model with fields null in the pre-approve?

**Comment by victorlap** [comment]
Hi @asivaneswaran Thank you for taking time to explore this issue.

One caveat with creating a model with all `null` values is that not all columns are nullable, and therefore this seems like a sub-par solution.

I think a more useful approach would be to just create an approval record, without a reference to a model. That way, we can create the model once you approve() the approval.

If you have any more ideas, or a simple way to add this, PR's are welcome! Otherwise I think I may come up with a solution this weekend.

**Comment by darrencoutts118** [comment]
@victorlap - did you manage to find a solution to this?

**Comment by victorlap** [comment]
Hey I did not yet look into this.

We could whip up a new table and store the data there. If you have time you are free to send a (tested) pull request!
